apiVersion: v1
kind: ReplicationController
metadata:
  name: tyk-gateway
  labels:
    name: tyk-gateway
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: tyk-gateway
    spec:
      containers:
      - name: tyk-gateway
        image: tykio/tyk-gateway:v2.3.0.31
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: gateway-git
          mountPath: /config
        command:
        - "/opt/tyk-gateway/tyk"
        - "--conf=/config/tyk-kubernetes/gateway.json"
        - "--debug"
      volumes:
      - name: gateway-git
        gitRepo:
          repository: "https://github.com/tonyhhyip/tyk-kubernetes"
