apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  labels:
    app: tyk
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: master
        image: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - name: redis
          containerPort: 6379
